# Generated by Django 6.0.8 on 2026-10-01 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_configure_default_group_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceCheckIn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_name_snapshot", models.CharField(max_length=255)),
                ("work_date", models.DateField()),
                ("scheduled_entry_time", models.TimeField(blank=True, null=True)),
                ("first_check_in_at", models.DateTimeField()),
                ("last_login_at", models.DateTimeField()),
                ("login_count", models.PositiveIntegerField(default=1)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("on_time", "A tiempo"), ("late", "Retraso"), ("no_schedule", "Sin horario")], max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="attendance_check_ins", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-work_date", "first_check_in_at"),
                "indexes": [models.Index(fields=["work_date", "status"], name="accounts_at_work_da_9c20e3_idx")],
                "constraints": [models.UniqueConstraint(fields=("user", "work_date"), name="unique_employee_daily_check_in")],
            },
        ),
        migrations.CreateModel(
            name="EmployeeWorkSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weekday", models.PositiveSmallIntegerField(choices=[(0, "Lunes"), (1, "Martes"), (2, "Miércoles"), (3, "Jueves"), (4, "Viernes"), (5, "Sábado"), (6, "Domingo")])),
                ("entry_time", models.TimeField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="work_schedules", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("weekday",),
                "constraints": [models.UniqueConstraint(fields=("user", "weekday"), name="unique_employee_schedule_weekday")],
            },
        ),
    ]
