# Generated by Django 6.0.8 on 2026-10-02 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_attendancecheckin_employeeworkschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mascot_look",
            field=models.CharField(
                choices=[
                    ("tierno", "Tierno"),
                    ("cartoon", "Cartoon"),
                    ("peluche", "Peluche"),
                ],
                default="tierno",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="LachiPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=160, verbose_name="Frase")),
                (
                    "moment",
                    models.CharField(
                        choices=[
                            ("poke", "Al tocarlo"),
                            ("new_order", "Llega un pedido nuevo"),
                            ("created", "Pedido registrado"),
                            ("completed", "Pedido completado"),
                            ("canceled", "Pedido cancelado"),
                            ("error", "Error"),
                            ("wake", "Al despertar"),
                        ],
                        default="poke",
                        max_length=20,
                        verbose_name="Cuándo la dice",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lachi_phrases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("moment", "id"),
            },
        ),
    ]
