# Generated by Django 6.0.8 on 2026-10-02 06:11

from django.db import migrations, models


KITCHEN_PHRASES = [
    "Tlabaja..!! -.-",
    "¡Comanda nueva! A la plancha, equipo",
    "Pedido entrando, ¡manos a la obra!",
    "¡Otro antojo por cumplir! Échenle sazón",
    "¡Fuego en la cocina! Llegó un pedido",
]


def seed_kitchen(apps, schema_editor):
    LachiPhrase = apps.get_model("accounts", "LachiPhrase")
    if not LachiPhrase.objects.filter(moment="kitchen").exists():
        LachiPhrase.objects.bulk_create(LachiPhrase(text=text, moment="kitchen") for text in KITCHEN_PHRASES)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_seed_lachi_phrases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lachiphrase",
            name="moment",
            field=models.CharField(
                choices=[
                    ("poke", "Al tocarlo"),
                    ("new_order", "Llega un pedido nuevo"),
                    ("created", "Pedido registrado"),
                    ("completed", "Pedido completado"),
                    ("canceled", "Pedido cancelado"),
                    ("error", "Error"),
                    ("wake", "Al despertar"),
                    ("kitchen", "Cocina: llega un pedido"),
                ],
                default="poke",
                max_length=20,
                verbose_name="Cuándo la dice",
            ),
        ),
        migrations.RunPython(seed_kitchen, migrations.RunPython.noop),
    ]
