# Generated by Django 6.0.8 on 2026-10-02 06:14

from django.db import migrations, models


def retire_tierno(apps, schema_editor):
    # El look "Tierno" se retiró: quienes lo tenían pasan a "Cartoon".
    apps.get_model("accounts", "Profile").objects.filter(mascot_look="tierno").update(mascot_look="cartoon")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_lachi_kitchen_moment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="mascot_look",
            field=models.CharField(
                choices=[
                    ("cartoon", "Cartoon"),
                    ("peluche", "Peluche"),
                    ("cartoon_halloween", "Cartoon Halloween"),
                    ("peluche_halloween", "Peluche Halloween"),
                ],
                default="cartoon",
                max_length=20,
            ),
        ),
        migrations.RunPython(retire_tierno, migrations.RunPython.noop),
    ]
