# Generated by Django 6.0.8 on 2026-08-26 04:57

import django.db.models.deletion
from django.db import migrations, models


def configure_category_packaging(apps, schema_editor):
    Category = apps.get_model("menu", "Category")
    PackagingType = apps.get_model("menu", "PackagingType")
    Product = apps.get_model("menu", "Product")
    beverage = PackagingType.objects.filter(name__icontains="bebida").first()
    if not beverage:
        beverage = PackagingType.objects.filter(name__icontains="vaso").first()
    general = PackagingType.objects.filter(name__icontains="general").first()
    for category in Category.objects.all():
        normalized = category.name.casefold()
        is_beverage = any(word in normalized for word in ("bebida", "café", "cafe", "fría", "fria", "caliente"))
        packaging = beverage if is_beverage else general
        if packaging:
            category.default_packaging_type = packaging
            category.save(update_fields=["default_packaging_type"])
            Product.objects.filter(category=category).update(packaging_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_packaging_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="default_packaging_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="menu.packagingtype",
            ),
        ),
        migrations.RunPython(configure_category_packaging, migrations.RunPython.noop),
    ]
