# Generated by Django 6.0.8 on 2026-09-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_category_default_packaging_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="preparation_station",
            field=models.CharField(
                choices=[("cold", "Barra fría"), ("hot", "Barra caliente")],
                default="hot",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="preparation_station",
            field=models.CharField(
                blank=True,
                choices=[("cold", "Barra fría"), ("hot", "Barra caliente")],
                default="",
                help_text="Déjalo vacío para utilizar la barra configurada en la categoría.",
                max_length=10,
            ),
        ),
    ]
