# Generated by Django 6.0.8 on 2026-09-22 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_category_preparation_station_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_position_x",
            field=models.PositiveSmallIntegerField(
                default=50, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_position_y",
            field=models.PositiveSmallIntegerField(
                default=50, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_zoom",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
