# Generated by Django 6.0.8 on 2026-09-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_product_image_position_x_product_image_position_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption",
            name="replacement_pair",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
