# Generated by Django 6.0.8 on 2026-08-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyOrderCounter",
            fields=[
                ("operating_date", models.DateField(primary_key=True, serialize=False)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
