# Generated by Django 6.0.8 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_dailyordercounter"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCustomer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("normalized_name", models.CharField(editable=False, max_length=150, unique=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("street", models.CharField(blank=True, max_length=150)),
                ("exterior_number", models.CharField(blank=True, max_length=20)),
                ("interior_number", models.CharField(blank=True, max_length=20)),
                ("neighborhood", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
    ]
