# Generated by Django 6.0.8 on 2026-09-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_cash_received_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cold_bar_status",
            field=models.CharField(
                choices=[("pending", "Pendiente"), ("completed", "Terminada")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="hot_bar_status",
            field=models.CharField(
                choices=[("pending", "Pendiente"), ("completed", "Terminada")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="preparation_station_snapshot",
            field=models.CharField(
                choices=[("cold", "Barra fría"), ("hot", "Barra caliente")],
                default="hot",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="preparation_status",
            field=models.CharField(
                choices=[("pending", "Pendiente"), ("completed", "Terminada")],
                default="pending",
                max_length=12,
            ),
        ),
    ]
